name: 'Parepare archive'
description: 'Prepare an archive of a base Slackware filesystem'
runs:
  using: 'docker'
  image: 'ghcr.io/erikkugel/slackware64:latest'
  entrypoint: ./slackware64/prepare-base
