#!/bin/bash

set -e

SLACKWARE_MIRROR=${SLACKWARE_MIRROR:-https://mirrors.slackware.com/slackware/slackware64-15.0/}
BASE_DIR=$(dirname $0)
export ROOT=build

if [ -d ${ROOT} ]; then
	rm --force --recursive ${ROOT}
fi
mkdir --verbose ${ROOT}
if [ ! -d tar ]; then
	mkdir --verbose tar
fi

echo 'Preparing packages...'
echo YES | slackpkg update gpg
slackpkg -batch=on -default_answer=y update
slackpkg -batch=on -default_answer=y download ${BASE_DIR}/packages
for package in $(cat ${BASE_DIR}/packages); do
        find /var/cache/packages/slackware64 -name "${package}-*.txz" -exec installpkg {} \;
        find /var/cache/packages/patches/packages -name "${package}-*.txz" -exec upgradepkg {} \;
done
ldconfig -r ${ROOT}

echo 'Configuring Slackpkg...'
cp ${BASE_DIR}/slackpkg.conf ${ROOT}/etc/slackpkg/slackpkg.conf
echo ${SLACKWARE_MIRROR} > ${ROOT}/etc/slackpkg/mirrors
wget "${SLACKWARE_MIRROR}GPG-KEY" -O ${ROOT}/GPG-KEY
cat << EOF | chroot ${ROOT}
	update-ca-certificates -v -f
	( cat GPG-KEY | gpg --homedir /root/.gnupg --import ) && rm GPG-KEY
EOF

echo 'Archiving filesystem...'
pushd ${ROOT}
tar --numeric-owner \
	--exclude=dev \
	--exclude=proc \
	--exclude=sys \
	--create \
	--file ../tar/slackware64.tar *
popd

echo 'Done.'
