#!/bin/bash

set -e

SLACKWARE_MIRROR=${SLACKWARE_MIRROR:-https://mirrors.slackware.com/slackware/slackware64-15.0/}

BASE_DIR=$(dirname $0)
echo $0 PWD $(pwd)
echo $0 LS $(ls -lR)
ehoc $0 WHOAMI $(whoami)

if [ -d build ]; then
	rm --force --recursive build
fi
mkdir --verbose build
if [ ! -d tar ]; then
	mkdir --verbose tar
fi

echo 'Preparing packages...'
echo YES | slackpkg update gpg
slackpkg -batch=on -default_answer=y update
slackpkg -batch=on -default_answer=y download ${BASE_DIR}/packages
while IFS= read -r package; do
	find /var/cache/packages/slackware64 -name "${package}-*.txz" -exec installpkg --root build {} \;
	find /var/cache/packages/patches/packages -name "${package}-*.txz" -exec ROOT=build upgradepkg {} \;
done < ${BASE_DIR}/packages
ldconfig -r build

echo 'Configuring Slackpkg...'
cp ${BASE_DIR}/slackpkg.conf build/etc/slackpkg/slackpkg.conf
echo ${SLACKWARE_MIRROR} > build/etc/slackpkg/mirrors
wget "${SLACKWARE_MIRROR}GPG-KEY" -O build/GPG-KEY
cat << EOF | chroot build
	update-ca-certificates -v -f
	( cat GPG-KEY | gpg --homedir /root --import ) && rm GPG-KEY
EOF

echo 'Archiving filesystem...'
pushd build
tar --numeric-owner \
	--exclude=dev \
	--exclude=proc \
	--exclude=sys \
	--create \
	--file ../tar/slackware64.tar *
popd

echo 'Done.'
