name: slackware-base-image-update
run-name: Update Slackware base image
on:
  push:
    branches:
      - 'release/*'
    path:
      - 'slackware64-base/**'
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build
        run: |
          cd slackware64-base
          docker build --tag "ghcr.io/erikkugel/slackware64-base:$(date +%Y%m%d)" .
      - name: Push
        run: docker push "ghcr.io/erikkugel/slackware64-base:$(date +%Y%m%d)"
