name: slackware-base-image-update
run-name: Update Slackware base image
on:
  workflow_dispatch:

jobs:
  update-image:
    name: Update image
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare archive
        uses: ./slackware64
        
      - name: Import
        run: cat tar/slackware64.tar | docker import - slackware64

      - name: Verify
        run: docker run slackware64:latest slackpkg update

      - name: Tag
        run: |
          docker tag slackware64 "ghcr.io/${{ github.repository_owner }}/slackware64:$(date +%Y%m%d)"
          docker tag slackware64 "ghcr.io/${{ github.repository_owner }}/slackware64:$(docker run slackware64 cat /etc/slackware-version | grep -o '[0-9]*\.[0-9]*$')"
          docker tag slackware64 "ghcr.io/${{ github.repository_owner }}/slackware64:latest"

      - name: Push
        run: docker image push --all-tags "ghcr.io/${{ github.repository_owner }}/slackware64"
