name: slackware-base-image-update
run-name: Update Slackware base image
on:
  workflow_dispatch:

jobs:
  update-image:
    name: Update image
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Docker image
        id: build
        uses: ./slackware64

      - name: Debug
        run: ls -lR ${GITHUB_WORKSPACE}
  
#      - name: Build
#        run: |
#          cd ./slackware64-base
#          TIMESTAMP_TAG="$(date +%Y%m%d)"
#          echo "TIMESTAMP_TAG=${TIMESTAMP_TAG}" >> $GITHUB_ENV
#          docker build --tag slackware64-base .
#
#      - name: Tag
#        run: |
#          SLACKWARE_VERSION_TAG="$(docker run docker.io/library/slackware64-base 'grep --only-matching --perl-regexp [0-9]*\.[0-9]*$ /etc/slackware-version')"
#          docker tag docker.io/library/slackware64-base "ghcr.io/${{ github.repository_owner }}/slackware64-base:${{ env.TIMESTAMP_TAG }}"
#          docker tag docker.io/library/slackware64-base "ghcr.io/${{ github.repository_owner }}/slackware64-base:${SLACKWARE_VERSION_TAG}"
#          docker tag docker.io/library/slackware64-base "ghcr.io/${{ github.repository_owner }}/slackware64-base:latest"
#
#      - name: Push
#        run: docker image push --all-tags "ghcr.io/${{ github.repository_owner }}/slackware64-base"
