name: slackware-base-image-update
run-name: Update Slackware base image
on:
  push:
    branches:
      - 'release/*'
    path:
      - 'slackware64-base/**'
      - '!slackware64-base/README.md'
  workflow_dispatch:

jobs:
  update-image:
    name: Update Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    outputs:
      image_tag: ${{ steps.step1.outputs.test }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          IMAGE_TAG="$(date +%Y%m%d)"
          echo "image-tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
          cd slackware64-base
          docker build --tag "ghcr.io/erikkugel/slackware64-base:$IMAGE_TAG" .\
      - name: Push
        run: docker push "ghcr.io/erikkugel/slackware64-base:${{ needs.build-image.outputs.image-tag }}"
