name: slackware-base-image-update
run-name: Update Slackware base image
on:
  push:
    branches:
      - 'release/*'
    path:
      - 'slackware64-base/**'
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd slackware64-base
          docker build --tag "slackware64-base:$(date +%Y%m%d)" .
