name: slackware-base-image-update
run-name: Update Slackware base image
on:
  push:
    branches:
      - 'release/*'
    path:
      - 'slackware64-base/**'
  workflow_dispatch:

jobs:
  update-image:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    outputs:
      image_tag: ${{ steps.step1.outputs.test }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #- name: Log in to registry
      #  run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      #- name: Set Tag
      #  run: echo "IMAGE_TAG=$(date +%Y%m%d)" >> $GITHUB_ENV
      - name: Build
        run: |
          IMAGE_TAG="$(date +%Y%m%d)"
          echo "image-tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
          cd slackware64-base
          docker build --tag "ghcr.io/erikkugel/slackware64-base:$IMAGE_TAG" .\
      - name: Push
        run: docker image ls
      #  run: docker push "ghcr.io/erikkugel/slackware64-base:${{ needs.build-image.outputs.image_tag }}"
